[package]
name = "osx-clnr"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "oclnr"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
ignore = "0.4"
rayon = "1"
dirs = "5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
indicatif = "0.17"
chrono = { version = "0.4", features = ["serde"] }
dashmap = "6"
jwalk = "0.8"
wasm4pm-compat = { version = "26.6.8", features = ["formats", "strict"] }
blake3 = "1.8.5"
dialoguer = "0.12.0"
colored = "3.1.1"
clap_complete = "4.6.5"
which = "8.0.3"

[dev-dependencies]
tempfile = "3"

