//! Disk-scan-derived classifier classes (CLASSIFIER_REVISION r7).
//!
//! Encodes the 2026-10-08 15-lane disk-scan nomination corpus as pure domain
//! predicates. All functions are pure: they take inert snapshots/primitives
//! and touch no filesystem — the integration layer supplies mtimes, sizes,
//! and child listings via `EntrySnapshot`/`DirSnapshot` and stat data.
//!
//! Two policy tiers:
//! - **Reversible (auto)**: safe to fold into a plan's auto-approve tier.
//! - **Operator-call**: `nominate-only`, never auto-deleted; each item needs an
//!   action outside the scanner's authority (in-VM prune, model repull,
//!   SHA-invalidating history rewrite, user re-download).

use std::path::{Path, PathBuf};

use crate::domain::artifact::{Candidate, DirSnapshot};

// ── TCC gate ───────────────────────────────────────────────────────────────────

/// Returns true when `path` is inside a TCC-protected subtree the process
/// cannot read (e.g. `~/Library/Mail`, `~/.Trash`). Callers must **skip and
/// report** these, never error and never retry — an unreadable path is not
/// evidence of absence of candidates, it is a bounded gap in coverage.
///
/// # Examples
///
/// ```
/// use osx_clnr::domain::disk_scan::is_tcc_gate_path;
/// use std::path::Path;
///
/// // Positive: unreadable-without-consent subtrees are gated.
/// assert!(is_tcc_gate_path(Path::new("/Users/j/Library/Mail")));
/// assert!(is_tcc_gate_path(Path::new("/Users/j/Library/Mail/V9")));
/// assert!(is_tcc_gate_path(Path::new("/Users/j/.Trash/junk")));
///
/// // Negative: scannable tool roots are not gated.
/// assert!(!is_tcc_gate_path(Path::new("/Users/j/Library/Caches/go-build")));
/// assert!(!is_tcc_gate_path(Path::new("/Users/j/proj/target")));
/// ```
pub fn is_tcc_gate_path(path: &Path) -> bool {
    let s = path.to_string_lossy();
    s.contains("/Library/Mail") || s.ends_with("/.Trash") || s.contains("/.Trash/")
}

// ── Reversible (auto) classes ──────────────────────────────────────────────────

/// Reversible class: a repo-root `erl_crash.dump` (witnessed: erlmcp-style
/// roots accumulate large crash dumps at the project root). Diagnostics
/// output of a past crash — not an input to anything; rebuildable by
/// absence. Extends the erlang-project-scoped rule already in
/// `artifact_candidates_from_snapshot` to any root.
///
/// # Examples
///
/// ```
/// use osx_clnr::domain::disk_scan::erl_crash_dump_candidate;
/// use osx_clnr::domain::artifact::{DirSnapshot, EntryKind, EntrySnapshot};
/// use std::path::{Path, PathBuf};
///
/// let snap = DirSnapshot {
///     children: vec![EntrySnapshot::new(
///         PathBuf::from("/repo/erl_crash.dump"),
///         "erl_crash.dump".into(),
///         Some("dump".into()),
///         EntryKind::File,
///     )],
/// };
/// // Positive: root-level crash dump is nominated.
/// let c = erl_crash_dump_candidate(Path::new("/repo"), &snap).unwrap();
/// assert_eq!(c.path, PathBuf::from("/repo/erl_crash.dump"));
/// assert_eq!(c.reason, "erlang crash dump (repo root)");
///
/// // Negative: no dump, no nomination.
/// assert!(erl_crash_dump_candidate(Path::new("/repo"), &DirSnapshot::default()).is_none());
/// ```
pub fn erl_crash_dump_candidate(root: &Path, snap: &DirSnapshot) -> Option<Candidate> {
    if snap.has_file("erl_crash.dump") {
        return Some(Candidate {
            path: root.join("erl_crash.dump"),
            reason: "erlang crash dump (repo root)".to_string(),
        });
    }
    None
}

/// Reversible class: `ios/build` and `ios/Pods` under a project root that has
/// a `Podfile.lock` (witnessed: zoela, 6.8 GB). Both are regenerated by
/// `xcodebuild`/`pod install` from the lockfile.
///
/// # Examples
///
/// ```
/// use osx_clnr::domain::disk_scan::ios_build_pods_candidates;
/// use osx_clnr::domain::artifact::{DirSnapshot, EntryKind, EntrySnapshot};
/// use std::path::{Path, PathBuf};
///
/// let snap = DirSnapshot {
///     children: vec![
///         EntrySnapshot::new(PathBuf::from("/z/Podfile.lock"), "Podfile.lock".into(), Some("lock".into()), EntryKind::File),
///         EntrySnapshot::new(PathBuf::from("/z/ios"), "ios".into(), None, EntryKind::Dir),
///     ],
/// };
/// // Positive: both regenerable subtrees are nominated.
/// let c = ios_build_pods_candidates(Path::new("/z"), &snap);
/// assert_eq!(c.len(), 2);
/// assert!(c.iter().any(|x| x.path == PathBuf::from("/z/ios/build")));
/// assert!(c.iter().any(|x| x.path == PathBuf::from("/z/ios/Pods")));
///
/// // Negative: no Podfile.lock → no nomination (an ios/ dir alone is not signal).
/// let no_lock = DirSnapshot {
///     children: vec![EntrySnapshot::new(PathBuf::from("/z/ios"), "ios".into(), None, EntryKind::Dir)],
/// };
/// assert!(ios_build_pods_candidates(Path::new("/z"), &no_lock).is_empty());
///
/// // Negative: lockfile but no ios/ dir → nothing to nominate.
/// let no_ios = DirSnapshot {
///     children: vec![EntrySnapshot::new(PathBuf::from("/z/Podfile.lock"), "Podfile.lock".into(), Some("lock".into()), EntryKind::File)],
/// };
/// assert!(ios_build_pods_candidates(Path::new("/z"), &no_ios).is_empty());
/// ```
pub fn ios_build_pods_candidates(root: &Path, snap: &DirSnapshot) -> Vec<Candidate> {
    let mut out = Vec::new();
    if snap.has_file("Podfile.lock") && snap.has_dir("ios") {
        for rel in ["build", "Pods"] {
            out.push(Candidate {
                path: root.join("ios").join(rel),
                reason: "ios build/pods (regenerable from Podfile.lock)".to_string(),
            });
        }
    }
    out
}

/// Reversible class decision: a vendored `node_modules` is stale when its
/// upstream mtime/commit is older than 2 years (class
/// `node_modules_stale_vendor`).
///
/// # Examples
///
/// ```
/// use osx_clnr::domain::disk_scan::node_modules_stale;
///
/// // Positive: 3-year-old vendored tree is stale.
/// assert!(node_modules_stale(3 * 365 * 86_400));
///
/// // Negative: fresh vendored tree is not.
/// assert!(!node_modules_stale(86_400));
///
/// // Refusal boundary: exactly 2 years is not yet stale.
/// assert!(!node_modules_stale(2 * 365 * 86_400));
/// ```
pub fn node_modules_stale(age_secs: i64) -> bool {
    age_secs > 2 * 365 * 86_400
}

/// Reversible class decision for `venv_stale`: a `.venv` is nominatable only
/// when BOTH (a) no doc reference exists — the README/CLAUDE/justfile/AGENTS
/// grep IS the documented-toolchain gate — AND (b) last use is older than 30
/// days. A documented venv is a KEEP regardless of age (witnessed: autofde
/// documented-KEEP vs mfw stale).
///
/// # Examples
///
/// ```
/// use osx_clnr::domain::disk_scan::venv_stale;
///
/// // Positive: unreferenced + 45d unused → nominate.
/// assert!(venv_stale(false, 45));
///
/// // Negative: documented toolchain → KEEP even at 2 years.
/// assert!(!venv_stale(true, 730));
///
/// // Negative: recent use → keep.
/// assert!(!venv_stale(false, 3));
///
/// // Refusal boundary: exactly 30d is not yet stale.
/// assert!(!venv_stale(false, 30));
/// ```
pub fn venv_stale(doc_referenced: bool, last_use_age_days: u64) -> bool {
    !doc_referenced && last_use_age_days > 30
}

/// Reversible class: orphaned `node_modules` — a `node_modules` directory with
/// no package manifest (`package.json`, `package-lock.json`, `yarn.lock`,
/// `pnpm-lock.yaml`, `bun.lockb`) in its enclosing manifest scope. Witnessed:
/// a stray `~/node_modules` (1.9 GB) with no manifest anywhere near it.
///
/// `snap` is the listing of the nearest enclosing directory that could hold
/// the manifest; the caller walks up to find that scope.
///
/// # Examples
///
/// ```
/// use osx_clnr::domain::disk_scan::is_orphan_node_modules;
/// use osx_clnr::domain::artifact::{DirSnapshot, EntryKind, EntrySnapshot};
/// use std::path::PathBuf;
///
/// // Positive: node_modules present, no manifest anywhere in scope.
/// let snap = DirSnapshot {
///     children: vec![EntrySnapshot::new(PathBuf::from("/h/node_modules"), "node_modules".into(), None, EntryKind::Dir)],
/// };
/// assert!(is_orphan_node_modules(&snap));
///
/// // Negative: package.json sibling → legitimate dependency tree.
/// let owned = DirSnapshot {
///     children: vec![
///         EntrySnapshot::new(PathBuf::from("/h/package.json"), "package.json".into(), Some("json".into()), EntryKind::File),
///         EntrySnapshot::new(PathBuf::from("/h/node_modules"), "node_modules".into(), None, EntryKind::Dir),
///     ],
/// };
/// assert!(!is_orphan_node_modules(&owned));
///
/// // Negative: lockfile-only scope (manifest regenerated elsewhere) still owns it.
/// let locked = DirSnapshot {
///     children: vec![
///         EntrySnapshot::new(PathBuf::from("/h/pnpm-lock.yaml"), "pnpm-lock.yaml".into(), Some("yaml".into()), EntryKind::File),
///         EntrySnapshot::new(PathBuf::from("/h/node_modules"), "node_modules".into(), None, EntryKind::Dir),
///     ],
/// };
/// assert!(!is_orphan_node_modules(&locked));
/// ```
pub fn is_orphan_node_modules(snap: &DirSnapshot) -> bool {
    snap.has_dir("node_modules")
        && !snap.has_file("package.json")
        && !snap.has_file("package-lock.json")
        && !snap.has_file("yarn.lock")
        && !snap.has_file("pnpm-lock.yaml")
        && !snap.has_file("bun.lockb")
}

/// Reversible class: lane build roots under `$TMPDIR` or `~/.cache/tmp`
/// (witnessed: `~/.cache/tmp/base-2/runs/x/_build`, 2.6 GB across xaas
/// roots). Extends the `_build-lane*` fan-out lease rule: a build-root-named
/// directory living under a `tmp` component is scratch, not a live lease —
/// tmp regimes are scrubbed wholesale, so nothing canonical lives there.
///
/// # Examples
///
/// ```
/// use osx_clnr::domain::disk_scan::is_tmp_lane_build_root;
/// use std::path::Path;
///
/// // Positive: build roots under tmp scratch areas.
/// assert!(is_tmp_lane_build_root(Path::new("/Users/j/.cache/tmp/base-2/runs/x/_build")));
/// assert!(is_tmp_lane_build_root(Path::new("/private/tmp/laneA/_build-laneW984dj")));
/// assert!(is_tmp_lane_build_root(Path::new("/var/folders/aa/T/target")));
///
/// // Negative: the canonical checkout's own build dirs are NOT tmp roots.
/// assert!(!is_tmp_lane_build_root(Path::new("/Users/j/xaas/_build")));
/// assert!(!is_tmp_lane_build_root(Path::new("/Users/j/xaas/_build-laneX")));
/// assert!(!is_tmp_lane_build_root(Path::new("/Users/j/osx-clnr/target")));
///
/// // Refusal: no tmp component → out of scope for this class.
/// assert!(!is_tmp_lane_build_root(Path::new("/Users/j/proj/deps")));
/// ```
pub fn is_tmp_lane_build_root(path: &Path) -> bool {
    let comps: Vec<&str> = path.components().filter_map(|c| c.as_os_str().to_str()).collect();
    let under_tmp = comps.iter().any(|c| *c == "tmp" || *c == "T");
    if !under_tmp {
        return false;
    }
    let last = comps.last().copied().unwrap_or("");
    crate::domain::artifact::is_artifact_leaf_name(last)
}

/// Reversible class: git's interrupted-repack temporaries —
/// `.git/objects/pack/tmp_pack_*` (witnessed: `tmp_pack_QIkM2S`, 607 MB).
/// A `tmp_pack_*` survives only a crashed/interrupted `git gc`/fetch; git
/// never reads it back and recreates it on the next repack.
///
/// # Examples
///
/// ```
/// use osx_clnr::domain::disk_scan::is_tmp_pack_file;
/// use std::path::Path;
///
/// assert!(is_tmp_pack_file(Path::new("/Users/j/erlmcp/.git/objects/pack/tmp_pack_QIkM2S")));
///
/// // Negative: real pack files are not temporaries.
/// assert!(!is_tmp_pack_file(Path::new("/Users/j/erlmcp/.git/objects/pack/pack-abc123.pack")));
///
/// // Negative: a tmp_pack outside .git is out of scope.
/// assert!(!is_tmp_pack_file(Path::new("/Users/j/tmp/tmp_pack_QIkM2S")));
/// ```
pub fn is_tmp_pack_file(path: &Path) -> bool {
    path.to_string_lossy().contains("/.git/objects/pack/tmp_pack_")
}

// ── Reversible (auto): Electron HTTP caches ────────────────────────────────────

/// Reversible class: Electron app-bundle HTTP caches — `Cache/`,
/// `Code Cache/`, `GPUCache/` directories inside an `.app` bundle.
/// **Refusal**: if a `Service Worker/` directory is a sibling (same parent),
/// the nomination is refused — deleting the HTTP cache while a service worker
/// holds registrations corrupts the app's offline state; the operator must
/// clear the family together via the app itself.
///
/// # Examples
///
/// ```
/// use osx_clnr::domain::disk_scan::{is_electron_http_cache_dir, electron_cache_refused};
/// use std::path::Path;
///
/// // Positive: HTTP-cache dirs inside an app bundle.
/// assert!(is_electron_http_cache_dir(Path::new(
///     "/Applications/Zed.app/Contents/Resources/app/Cache"
/// )));
/// assert!(is_electron_http_cache_dir(Path::new(
///     "/Applications/Zed.app/Contents/Resources/app/Code Cache"
/// )));
/// assert!(is_electron_http_cache_dir(Path::new(
///     "/Applications/Zed.app/Contents/Resources/app/GPUCache"
/// )));
///
/// // Negative: an arbitrary Cache dir outside an .app bundle is out of scope.
/// assert!(!is_electron_http_cache_dir(Path::new("/Users/j/proj/Cache")));
///
/// // Refusal: a Service Worker sibling refuses the nomination.
/// assert!(electron_cache_refused(Path::new("/App/Z.app/Contents/a/Cache"), true));
/// assert!(!electron_cache_refused(Path::new("/App/Z.app/Contents/a/Cache"), false));
/// ```
pub fn is_electron_http_cache_dir(path: &Path) -> bool {
    let name = path.file_name().map(|n| n.to_string_lossy().to_string()).unwrap_or_default();
    let in_app = path.components().any(|c| c.as_os_str().to_string_lossy().ends_with(".app"));
    in_app && matches!(name.as_str(), "Cache" | "Code Cache" | "GPUCache")
}

/// Refusal half of the Electron HTTP-cache class: a `Service Worker/` sibling
/// refuses the whole nomination (see `is_electron_http_cache_dir`).
pub fn electron_cache_refused(path: &Path, has_service_worker_sibling: bool) -> bool {
    has_service_worker_sibling && is_electron_http_cache_dir(path)
}

// ── Reversible (auto): build-tool caches ───────────────────────────────────────

/// Reversible class: named build-tool caches under `~/Library/Caches` plus the
/// terraform provider cache. Extends `global_cache_candidates` with the
/// 2026-10-08 scan corpus: dotslash, wasmtime, node-gyp, pyinstaller, and
/// `.terraform/providers` (witnessed: `.terraform` x15).
///
/// dotslash materializes **signed `.app` contents**; the caller must skip
/// unreadable subpaths during sizing and report the nomination as partial.
///
/// # Examples
///
/// ```
/// use osx_clnr::domain::disk_scan::build_tool_cache_candidates;
/// use std::path::Path;
///
/// let home = Path::new("/Users/j");
/// let c = build_tool_cache_candidates(home);
///
/// // Positive: the new named caches.
/// assert!(c.iter().any(|(p, _)| p == Path::new("/Users/j/Library/Caches/dotslash")));
/// assert!(c.iter().any(|(p, _)| p == Path::new("/Users/j/Library/Caches/BytecodeAlliance.wasmtime")));
/// assert!(c.iter().any(|(p, _)| p == Path::new("/Users/j/Library/Caches/node-gyp")));
/// assert!(c.iter().any(|(p, _)| p == Path::new("/Users/j/Library/Caches/pyinstaller")));
/// assert!(c.iter().any(|(p, _)| p == Path::new("/Users/j/.terraform/providers")));
///
/// // Refusal: nothing outside home.
/// assert!(c.iter().all(|(p, _)| p.starts_with(home)));
/// ```
pub fn build_tool_cache_candidates(home: &Path) -> Vec<(PathBuf, String)> {
    [
        (
            "Library/Caches/Mozilla.sccache",
            "sccache compiler cache",
        ),
        (
            "Library/Caches/dotslash",
            "dotslash materialization cache (signed .app contents — skip unreadable subpaths, report partial)",
        ),
        (
            "Library/Caches/BytecodeAlliance.wasmtime",
            "wasmtime build cache",
        ),
        ("Library/Caches/node-gyp", "node-gyp headers/toolchain cache"),
        ("Library/Caches/pyinstaller", "pyinstaller bootloader cache"),
        (".terraform/providers", "terraform provider cache"),
    ]
    .iter()
    .map(|(rel, reason)| (home.join(rel), reason.to_string()))
    .collect()
}

/// Reversible-class predicate for the `*-updater` cache family: any
/// `~/Library/Caches/<name>-updater` directory (electron-updater convention).
///
/// # Examples
///
/// ```
/// use osx_clnr::domain::disk_scan::is_updater_cache_dirname;
///
/// assert!(is_updater_cache_dirname("com.squareup.conduit-updater"));
/// assert!(is_updater_cache_dirname("zoom-updater"));
/// assert!(!is_updater_cache_dirname("Homebrew"));
/// assert!(!is_updater_cache_dirname("updater")); // bare, no <name>- prefix
/// ```
pub fn is_updater_cache_dirname(name: &str) -> bool {
    name.len() > "-updater".len() && name.ends_with("-updater")
}

// ── Backup triplication (nominate keep-newest) ─────────────────────────────────

/// Nominate-only class: same-day, same-size tarball triplication (witnessed:
/// erlmcp backups — three copies of the same archive written the same day).
/// Returns the paths to nominate for deletion — **all but the newest** of each
/// `(size, day)` group. `--aggressive` gates actual deletion; the nomination
/// itself always fires so the plan records the duplication.
///
/// Entries are `(path, size_bytes, mtime_epoch_secs)`.
///
/// # Examples
///
/// ```
/// use osx_clnr::domain::disk_scan::triplicate_nominate;
/// use std::path::PathBuf;
///
/// // Three same-day, same-size erlmcp tarballs; the 14:00 one is newest.
/// let day = 1_760_000_000; // any epoch base; day bucketing is internal
/// let backups = vec![
///     (PathBuf::from("/b/erlmcp-a.tar.gz"), 1_073_741_824, day),
///     (PathBuf::from("/b/erlmcp-b.tar.gz"), 1_073_741_824, day + 3600),
///     (PathBuf::from("/b/erlmcp-c.tar.gz"), 1_073_741_824, day + 7200),
/// ];
/// let kill = triplicate_nominate(&backups);
/// assert_eq!(kill.len(), 2);
/// assert!(kill.contains(&PathBuf::from("/b/erlmcp-a.tar.gz")));
/// assert!(!kill.contains(&PathBuf::from("/b/erlmcp-c.tar.gz")));
///
/// // Negative: differing sizes are distinct archives — nothing nominated.
/// let distinct = vec![
///     (PathBuf::from("/b/a.tar.gz"), 100, day),
///     (PathBuf::from("/b/b.tar.gz"), 200, day),
/// ];
/// assert!(triplicate_nominate(&distinct).is_empty());
///
/// // Refusal: a single archive is never nominated.
/// assert!(triplicate_nominate(&[(PathBuf::from("/b/solo.tar.gz"), 5, day)]).is_empty());
/// ```
pub fn triplicate_nominate(entries: &[(PathBuf, u64, i64)]) -> Vec<PathBuf> {
    use std::collections::HashMap;
    let mut groups: HashMap<(u64, i64), Vec<usize>> = HashMap::new();
    for (i, (_, size, mtime)) in entries.iter().enumerate() {
        groups.entry((*size, mtime / 86_400)).or_default().push(i);
    }
    let mut kill = Vec::new();
    for mut idxs in groups.into_values() {
        if idxs.len() < 2 {
            continue;
        }
        idxs.sort_by_key(|&i| entries[i].2);
        for &i in &idxs[..idxs.len() - 1] {
            kill.push(entries[i].0.clone());
        }
    }
    kill
}

// ── Operator-call classes (nominate-only, never auto) ──────────────────────────

/// True when `reason` names an operator-call class: nominated for human review
/// only, never eligible for auto-approval. Each class needs an action outside
/// the scanner's authority:
///
/// - `colima datadisk`: in-VM prune needs `colima stop` + disk compact.
/// - `model weights`: public HF/ollama weights re-download on demand.
/// - `simulator devices`: `xcrun simctl` device state, not plain files.
/// - `installer`: Downloads installers — user confirms re-download.
/// - `history giant blob`: rewriting git history invalidates SHAs/receipts.
/// - `stale archive`: root-level archives the operator may still want.
///
/// # Examples
///
/// ```
/// use osx_clnr::domain::disk_scan::is_operator_call_reason;
///
/// assert!(is_operator_call_reason("colima datadisk (needs stop+compact)"));
/// assert!(is_operator_call_reason("model weights (repullable)"));
/// assert!(is_operator_call_reason("simulator devices (CoreSimulator)"));
/// assert!(is_operator_call_reason("installer dmg (Downloads, 200 MB)"));
/// assert!(is_operator_call_reason("history giant blob (rewrites SHAs)"));
/// assert!(is_operator_call_reason("stale archive (988 MB, 200d)"));
/// assert!(!is_operator_call_reason("rust target"));
/// assert!(!is_operator_call_reason("node dependencies"));
/// ```
pub fn is_operator_call_reason(reason: &str) -> bool {
    const OPS: [&str; 6] = [
        "colima datadisk",
        "model weights",
        "simulator devices",
        "installer",
        "history giant blob",
        "stale archive",
    ];
    OPS.iter().any(|op| reason.contains(op))
}

/// Operator-call class gate: a Downloads installer (`*.dmg`/`*.pkg`) larger
/// than 100 MB (witnessed class `installer_dmg`).
///
/// # Examples
///
/// ```
/// use osx_clnr::domain::disk_scan::is_installer_dmg;
/// use std::path::Path;
///
/// assert!(is_installer_dmg(Path::new("/Users/j/Downloads/Xcode_16.dmg"), 200_000_000));
/// // Too small.
/// assert!(!is_installer_dmg(Path::new("/Users/j/Downloads/notes.dmg"), 5_000_000));
/// // Wrong extension.
/// assert!(!is_installer_dmg(Path::new("/Users/j/Downloads/big.zip"), 200_000_000));
/// ```
pub fn is_installer_dmg(path: &Path, size_bytes: u64) -> bool {
    let ext = path.extension().map(|e| e.to_string_lossy().to_lowercase()).unwrap_or_default();
    matches!(ext.as_str(), "dmg" | "pkg") && size_bytes > 100 * 1024 * 1024
}

/// Operator-call class gate: a home-root-level archive larger than 500 MB
/// whose mtime is older than 6 months (witnessed: `Archive 3.zip` 988 MB,
/// `backup-critical` 1.3 GB). Nominate-only: the operator decides.
///
/// "Home-root-level" means directly in `$HOME` or in Downloads/Desktop/
/// Documents — not buried in a project tree.
///
/// # Examples
///
/// ```
/// use osx_clnr::domain::disk_scan::is_stale_archive;
/// use std::path::Path;
///
/// assert!(is_stale_archive(Path::new("/Users/j/Archive 3.zip"), 988 * 1024 * 1024, 200));
/// assert!(is_stale_archive(Path::new("/Users/j/Downloads/backup-critical.tar.gz"), 1_300_000_000, 365));
/// // Too small.
/// assert!(!is_stale_archive(Path::new("/Users/j/small.zip"), 100 * 1024 * 1024, 200));
/// // Too recent.
/// assert!(!is_stale_archive(Path::new("/Users/j/Archive 3.zip"), 988 * 1024 * 1024, 30));
/// // Buried in a project tree — out of scope.
/// assert!(!is_stale_archive(Path::new("/Users/j/proj/old/archives/x.zip"), 988 * 1024 * 1024, 200));
/// ```
pub fn is_stale_archive(path: &Path, size_bytes: u64, age_days: i64) -> bool {
    let ext = path.extension().map(|e| e.to_string_lossy().to_lowercase()).unwrap_or_default();
    let name = path.file_name().map(|n| n.to_string_lossy().to_lowercase()).unwrap_or_default();
    let ext = if name.ends_with(".tar.gz") { "tar.gz".to_string() } else { ext };
    let root_level = path.parent().is_some_and(|p| {
        p == Path::new("/")
            // directly inside a home dir (`/Users/<name>`)
            || p.parent() == Some(Path::new("/Users"))
            || p.file_name()
                .is_some_and(|f| f == "Downloads" || f == "Desktop" || f == "Documents")
    });
    matches!(ext.as_str(), "zip" | "tar.gz" | "tgz" | "7z")
        && size_bytes > 500 * 1024 * 1024
        && age_days > 180
        && root_level
}

// ── Witnessed-case corpus tests (2026-10-08) ──────────────────────────────────

#[cfg(test)]
mod disk_scan_r7_tests {
    use super::*;
    use crate::domain::artifact::{EntryKind, EntrySnapshot};

    fn snap(children: Vec<EntrySnapshot>) -> DirSnapshot {
        DirSnapshot { children }
    }

    fn file(p: &str, name: &str) -> EntrySnapshot {
        EntrySnapshot::new(PathBuf::from(p), name.into(), None, EntryKind::File)
    }

    fn dir(p: &str, name: &str) -> EntrySnapshot {
        EntrySnapshot::new(PathBuf::from(p), name.into(), None, EntryKind::Dir)
    }

    /// Witnessed: stray `~/node_modules` (1.9 GB) with no manifest anywhere
    /// in its enclosing scope.
    #[test]
    fn witnessed_orphan_home_node_modules() {
        let s = snap(vec![dir("/Users/j/node_modules", "node_modules")]);
        assert!(is_orphan_node_modules(&s));
    }

    /// Witnessed: zoela ios tree (6.8 GB) — Podfile.lock present, ios/build +
    /// ios/Pods nominated together.
    #[test]
    fn witnessed_zoela_ios_build_pods() {
        let s = snap(vec![
            file("/Users/j/zoela/Podfile.lock", "Podfile.lock"),
            dir("/Users/j/zoela/ios", "ios"),
        ]);
        let c = ios_build_pods_candidates(Path::new("/Users/j/zoela"), &s);
        assert_eq!(c.len(), 2);
        assert!(c.iter().any(|x| x.path == Path::new("/Users/j/zoela/ios/build")));
        assert!(c.iter().any(|x| x.path == Path::new("/Users/j/zoela/ios/Pods")));
    }

    /// Witnessed pair: autofde's `.venv` is referenced by its docs
    /// (documented-KEEP, regardless of age); mfw's is unreferenced and
    /// 45 days cold (stale → nominate).
    #[test]
    fn witnessed_venv_autofde_keep_vs_mfw_stale() {
        assert!(!venv_stale(true, 400), "documented venv is a KEEP");
        assert!(venv_stale(false, 45), "unreferenced 45d venv is stale");
    }

    /// Witnessed: erlmcp same-day same-size tarball triplication — keep the
    /// newest, nominate the other two.
    #[test]
    fn witnessed_erlmcp_triplicate() {
        let day = 1_760_000_000;
        let backups = vec![
            (PathBuf::from("/Users/j/erlmcp/b1.tar.gz"), 1_073_741_824, day),
            (PathBuf::from("/Users/j/erlmcp/b2.tar.gz"), 1_073_741_824, day + 3600),
            (PathBuf::from("/Users/j/erlmcp/b3.tar.gz"), 1_073_741_824, day + 7200),
        ];
        let kill = triplicate_nominate(&backups);
        assert_eq!(kill.len(), 2);
        assert!(!kill.contains(&PathBuf::from("/Users/j/erlmcp/b3.tar.gz")));
    }

    /// Witnessed: `tmp_pack_QIkM2S` (607 MB) inside erlmcp's pack dir.
    #[test]
    fn witnessed_tmp_pack_qikm2s() {
        assert!(is_tmp_pack_file(Path::new("/Users/j/erlmcp/.git/objects/pack/tmp_pack_QIkM2S")));
    }

    /// Witnessed: `.terraform/providers` found in 15 repos — every
    /// build-tool-cache nomination set carries it.
    #[test]
    fn witnessed_terraform_providers_x15() {
        let c = build_tool_cache_candidates(Path::new("/Users/j"));
        assert!(c.iter().any(|(p, _)| p == Path::new("/Users/j/.terraform/providers")));
    }

    /// Witnessed: xaas lane roots under `~/.cache/tmp` (2.6 GB).
    #[test]
    fn witnessed_xaas_tmp_lane_roots() {
        assert!(is_tmp_lane_build_root(Path::new("/Users/j/.cache/tmp/base-2/runs/x/_build")));
        assert!(is_tmp_lane_build_root(Path::new("/Users/j/.cache/tmp/base-2/runs/x/deps")));
    }

    /// Refusal case witnessed in the corpus: an Electron HTTP cache with a
    /// `Service Worker/` sibling must be refused.
    #[test]
    fn witnessed_service_worker_refusal() {
        let p = Path::new("/Applications/Z.app/Contents/Resources/app/Cache");
        assert!(is_electron_http_cache_dir(p));
        assert!(electron_cache_refused(p, true));
    }

    /// TCC gate: Mail and .Trash are skip-and-report, never errors.
    #[test]
    fn tcc_gate_paths() {
        assert!(is_tcc_gate_path(Path::new("/Users/j/Library/Mail")));
        assert!(is_tcc_gate_path(Path::new("/Users/j/.Trash/x")));
        assert!(!is_tcc_gate_path(Path::new("/Users/j/Library/Caches")));
    }
}
