//! Policy loading via star-toml admission.
//!
//! The integration layer owns all filesystem access: this module reads
//! `osxclnr.toml` (or an explicit `--policy` path) and admits it through
//! `star_toml::TrustedLoader`, so the rest of the program only ever sees a
//! validated, normalized [`OclnrPolicy`]. Environment overrides use the
//! `OCLNR_` prefix (e.g. `OCLNR_RETENTION_HOURS=24`).

use std::{
    io::{Read, Write},
    path::{Path, PathBuf},
};

use anyhow::{anyhow, Context};
use star_toml::loader::TrustedLoader;

use crate::domain::policy::OclnrPolicy;

/// Environment variable that, if set, is used verbatim (UTF-8 bytes) as the
/// plan-approval HMAC secret. Takes priority over the on-disk key file so CI
/// and multi-machine setups can inject a shared secret without touching the
/// filesystem.
pub const APPROVAL_SECRET_ENV: &str = "OCLNR_APPROVAL_SECRET";

/// Sources the secret used to keyed-sign and verify [`PlanApproval`] HMACs
/// (`crate::domain::plan::PlanApproval`).
///
/// This is deliberately **not** derivable from anything an attacker who can
/// only write to a plan file can observe:
///
/// 1. If `OCLNR_APPROVAL_SECRET` is set, its bytes are used directly.
/// 2. Otherwise, a machine-local key file at `~/.oclnr/approval.key` is used.
///    If it doesn't exist yet, 32 random bytes are read from the OS CSPRNG
///    (`/dev/urandom` on Unix) and written to it with `0600` permissions
///    (parent directory `0700`), so only the owning user can read it — and
///    it lives outside any workspace or plan-file directory a script or
///    prompt-injected instruction could plausibly write to.
///
/// This function performs filesystem/OS I/O and therefore belongs in the
/// integration layer, not `domain::plan` — the domain only ever receives the
/// resulting secret bytes as a plain argument.
pub fn approval_secret() -> anyhow::Result<Vec<u8>> {
    if let Ok(from_env) = std::env::var(APPROVAL_SECRET_ENV) {
        if !from_env.is_empty() {
            return Ok(from_env.into_bytes());
        }
    }

    let key_path = approval_key_path()?;
    if key_path.exists() {
        let mut bytes = Vec::new();
        std::fs::File::open(&key_path)
            .with_context(|| format!("cannot open approval key file {}", key_path.display()))?
            .read_to_end(&mut bytes)
            .with_context(|| format!("cannot read approval key file {}", key_path.display()))?;
        if bytes.is_empty() {
            return Err(anyhow!("approval key file {} is empty", key_path.display()));
        }
        return Ok(bytes);
    }

    generate_and_persist_approval_key(&key_path)
}

/// Path to the machine-local approval secret file: `~/.oclnr/approval.key`.
fn approval_key_path() -> anyhow::Result<PathBuf> {
    let home = dirs_home()?;
    Ok(home.join(".oclnr").join("approval.key"))
}

fn dirs_home() -> anyhow::Result<PathBuf> {
    std::env::var_os("HOME")
        .map(PathBuf::from)
        .ok_or_else(|| anyhow!("cannot determine home directory (HOME is not set)"))
}

/// Generates 32 random bytes from the OS CSPRNG and persists them to
/// `key_path` with owner-only permissions, creating the parent directory
/// (also owner-only) if needed. Returns the generated bytes.
fn generate_and_persist_approval_key(key_path: &Path) -> anyhow::Result<Vec<u8>> {
    let parent = key_path.parent().ok_or_else(|| {
        anyhow!("approval key path {} has no parent directory", key_path.display())
    })?;
    std::fs::create_dir_all(parent)
        .with_context(|| format!("cannot create {}", parent.display()))?;

    let mut secret = vec![0u8; 32];
    std::fs::File::open("/dev/urandom")
        .context("cannot open /dev/urandom to generate approval secret")?
        .read_exact(&mut secret)
        .context("cannot read random bytes for approval secret")?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(parent, std::fs::Permissions::from_mode(0o700))
            .with_context(|| format!("cannot set permissions on {}", parent.display()))?;
    }

    let mut file = std::fs::OpenOptions::new();
    file.write(true).create_new(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        file.mode(0o600);
    }
    let mut opened = match file.open(key_path) {
        Ok(f) => f,
        // Race: another process created it between our `exists()` check and
        // now. Re-read what's there rather than clobbering it.
        Err(e) if e.kind() == std::io::ErrorKind::AlreadyExists => {
            let mut bytes = Vec::new();
            std::fs::File::open(key_path)
                .with_context(|| format!("cannot open approval key file {}", key_path.display()))?
                .read_to_end(&mut bytes)
                .with_context(|| format!("cannot read approval key file {}", key_path.display()))?;
            return Ok(bytes);
        }
        Err(e) => {
            return Err(e).with_context(|| format!("cannot create {}", key_path.display()));
        }
    };
    opened
        .write_all(&secret)
        .with_context(|| format!("cannot write approval key file {}", key_path.display()))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(key_path, std::fs::Permissions::from_mode(0o600))
            .with_context(|| format!("cannot set permissions on {}", key_path.display()))?;
    }

    Ok(secret)
}

/// Loads and admits the cleanup policy.
///
/// - `explicit`: a `--policy <path>` argument. The file must exist and admit
///   cleanly; failure is an error (the user asked for this exact policy).
/// - Otherwise `osxclnr.toml` in the current directory is layered in if
///   present; with no file at all, the built-in [`OclnrPolicy::default`] is
///   returned (after the same invariant check, so a broken default can never
///   ship silently).
pub fn load_policy(explicit: Option<&Path>) -> anyhow::Result<OclnrPolicy> {
    match explicit {
        Some(path) => {
            if !path.exists() {
                return Err(anyhow!("policy file not found: {}", path.display()));
            }
            admit_file(path)
        }
        None => {
            let default_path = Path::new("osxclnr.toml");
            if default_path.exists() {
                admit_file(default_path)
            } else {
                let policy = OclnrPolicy::default();
                let violations = policy.invariant_violations();
                if violations.is_empty() {
                    Ok(policy)
                } else {
                    Err(anyhow!("built-in default policy is invalid: {}", violations.join("; ")))
                }
            }
        }
    }
}

fn admit_file(path: &Path) -> anyhow::Result<OclnrPolicy> {
    TrustedLoader::new()
        .layer_file_if_exists(path)
        .env_prefix("OCLNR_")
        .load_admitted::<OclnrPolicy>()
        .map(|admitted| admitted.into_value())
        .with_context(|| format!("failed to admit policy from {}", path.display()))
}
