//! Integration modules.

pub mod backup;
pub mod brew;
pub mod config;
pub mod daemon_binary;
pub mod dedupe;
pub mod docker;
pub mod doctor;
pub mod fs;
pub mod git_health;
pub mod git_tracked;
pub mod github;
pub mod monitor;
pub mod notify;
pub mod ocl_store;
pub mod pressure;
pub mod progress;
pub mod r_projection;
pub mod scan_cache;
pub mod tmutil;
pub mod toolchain;
pub mod xcode;
