//! Time Machine (`tmutil`) integration layer.

use crate::domain::artifact::Candidate;
use std::fs;
use std::path::Path;

/// Writes a bash script that applies `tmutil addexclusion` to all directories.
pub fn write_tm_exclusions_script(
    script_path: &Path,
    candidates: &[Candidate],
) -> std::io::Result<()> {
    use std::io::Write;
    let mut file = fs::File::create(script_path)?;
    writeln!(file, "#!/bin/bash")?;
    writeln!(file, "# Generated by mac-artifact-cleaner")?;
    writeln!(file, "echo \"Applying Time Machine exclusions...\"")?;

    for c in candidates {
        if fs::symlink_metadata(&c.path)
            .map(|m| m.is_dir())
            .unwrap_or(false)
        {
            writeln!(file, "tmutil addexclusion \"{}\"", c.path.display())?;
        }
    }

    writeln!(file, "echo \"Done applying exclusions.\"")?;
    Ok(())
}

/// Executes a Time Machine exclusion script via bash.
pub fn apply_exclusions_script(script_path: &Path) -> anyhow::Result<()> {
    if !script_path.exists() {
        anyhow::bail!("Exclusion script does not exist: {}", script_path.display());
    }
    let status = std::process::Command::new("bash")
        .arg(script_path)
        .status()?;
    if !status.success() {
        anyhow::bail!("Exclusion script execution failed with status: {}", status);
    }
    Ok(())
}

/// Applies a Time Machine exclusion directly to a single path.
///
/// This tells macOS to avoid backing up this directory and prevents its contents
/// from bloating APFS snapshots. It is sticky, so if the directory is recreated
/// (e.g. `target/`), the exclusion remains active.
pub fn apply_single_exclusion(path: &Path) -> anyhow::Result<()> {
    // Note: We ignore the exit status because tmutil chokes on files that don't exist,
    // or if the volume doesn't support exclusions, but we don't want to block deletion.
    let _ = std::process::Command::new("tmutil")
        .args(["addexclusion", "-p"]) // -p makes it path-independent (sticky)
        .arg(path)
        .output();
    Ok(())
}

/// Lists all local APFS snapshots on the target mount point using `tmutil`.
pub fn list_local_snapshots(mount_point: &str) -> anyhow::Result<Vec<String>> {
    let output = std::process::Command::new("tmutil")
        .arg("listlocalsnapshots")
        .arg(mount_point)
        .output()?;
    if !output.status.success() {
        let err = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!("tmutil listlocalsnapshots failed: {}", err);
    }
    let stdout = String::from_utf8_lossy(&output.stdout);
    let mut snapshots = Vec::new();
    for line in stdout.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.contains("Snapshots for") {
            continue;
        }
        snapshots.push(trimmed.to_string());
    }
    Ok(snapshots)
}

/// Reclaims space by thinning local snapshots on the mount point.
pub fn thin_local_snapshots(mount_point: &str, bytes: u64, urgency: u8) -> anyhow::Result<String> {
    let output = std::process::Command::new("tmutil")
        .arg("thinlocalsnapshots")
        .arg(mount_point)
        .arg(bytes.to_string())
        .arg(urgency.to_string())
        .output()?;
    if !output.status.success() {
        let err = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!("tmutil thinlocalsnapshots failed: {}", err);
    }
    Ok(String::from_utf8_lossy(&output.stdout).to_string())
}
