//! Time Machine (`tmutil`) integration layer.

use crate::domain::artifact::Candidate;
use std::fs;
use std::path::Path;

/// Writes a bash script that applies `tmutil addexclusion` to all directories.
pub fn write_tm_exclusions_script(
    script_path: &Path,
    candidates: &[Candidate],
) -> std::io::Result<()> {
    use std::io::Write;
    let mut file = fs::File::create(script_path)?;
    writeln!(file, "#!/bin/bash")?;
    writeln!(file, "# Generated by osx-clnr")?;
    writeln!(file, "echo \"Applying Time Machine exclusions...\"")?;

    for c in candidates {
        if fs::symlink_metadata(&c.path)
            .map(|m| m.is_dir())
            .unwrap_or(false)
        {
            writeln!(file, "tmutil addexclusion \"{}\"", c.path.display())?;
        }
    }

    writeln!(file, "echo \"Done applying exclusions.\"")?;
    Ok(())
}

/// Executes a Time Machine exclusion script via bash.
pub fn apply_exclusions_script(script_path: &Path) -> anyhow::Result<()> {
    if !script_path.exists() {
        anyhow::bail!("Exclusion script does not exist: {}", script_path.display());
    }
    let status = std::process::Command::new("bash")
        .arg(script_path)
        .status()?;
    if !status.success() {
        anyhow::bail!("Exclusion script execution failed with status: {}", status);
    }
    Ok(())
}

/// Lists all local APFS snapshots on the target mount point using `tmutil`.
pub fn list_local_snapshots(mount_point: &str) -> anyhow::Result<Vec<String>> {
    let output = std::process::Command::new("tmutil")
        .arg("listlocalsnapshots")
        .arg(mount_point)
        .output()?;
    if !output.status.success() {
        let err = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!("tmutil listlocalsnapshots failed: {}", err);
    }
    let stdout = String::from_utf8_lossy(&output.stdout);
    let mut snapshots = Vec::new();
    for line in stdout.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.contains("Snapshots for") {
            continue;
        }
        snapshots.push(trimmed.to_string());
    }
    Ok(snapshots)
}

/// Reclaims space by thinning local snapshots on the mount point.
pub fn thin_local_snapshots(mount_point: &str, bytes: u64, urgency: u8) -> anyhow::Result<String> {
    let output = std::process::Command::new("tmutil")
        .arg("thinlocalsnapshots")
        .arg(mount_point)
        .arg(bytes.to_string())
        .arg(urgency.to_string())
        .output()?;
    if !output.status.success() {
        let err = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!("tmutil thinlocalsnapshots failed: {}", err);
    }
    Ok(String::from_utf8_lossy(&output.stdout).to_string())
}

/// Deletes a single local APFS snapshot by name or date via
/// `tmutil deletelocalsnapshots <name-or-date>`.
///
/// Unlike [`thin_local_snapshots`] (which lets macOS choose what to drop to hit a
/// byte target), this removes a specific snapshot the caller selected — e.g. the
/// oldest. Accepts either a full snapshot name or its date suffix (e.g.
/// `2026-05-26-135630`).
pub fn delete_local_snapshot(name_or_date: &str) -> anyhow::Result<String> {
    let output = std::process::Command::new("tmutil")
        .arg("deletelocalsnapshots")
        .arg(name_or_date)
        .output()?;
    if !output.status.success() {
        let err = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!(
            "tmutil deletelocalsnapshots {} failed: {}",
            name_or_date,
            err
        );
    }
    Ok(String::from_utf8_lossy(&output.stdout).to_string())
}
